// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5jo1FGR3ePIxfAJ107oV_lFJf7Vj8vLo',
    appId: '1:1008556669080:web:24abe46ca6a103e24e38ed',
    messagingSenderId: '1008556669080',
    projectId: 'apu-assignment',
    authDomain: 'apu-assignment.firebaseapp.com',
    storageBucket: 'apu-assignment.firebasestorage.app',
    measurementId: 'G-4G1QQ2Y881',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD_GG2p0lRWyg4az_z-sel92iXG1np5Ic',
    appId: '1:1008556669080:android:c861b08d4c7043b54e38ed',
    messagingSenderId: '1008556669080',
    projectId: 'apu-assignment',
    storageBucket: 'apu-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8EZjh_h6pY_e87-nzlIgvCW-syfQi_Us',
    appId: '1:1008556669080:ios:29d847255d0bb9814e38ed',
    messagingSenderId: '1008556669080',
    projectId: 'apu-assignment',
    storageBucket: 'apu-assignment.firebasestorage.app',
    iosBundleId: 'com.example.apuAssignment',
  );
}
